{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "form-recognizer.secretName" . }}
  labels:
    {{- include "form-recognizer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secretEnv.apikey }}
  apikey: {{ .Values.secretEnv.apikey | quote }}
  {{- end }}
  {{- if .Values.secretEnv.billing }}
  billing: {{ .Values.secretEnv.billing | quote }}
  {{- end }}
{{- end }}

