apiVersion: v1
kind: Secret
metadata:
  name: layout-form-recognizer-secret
  labels:
    app.kubernetes.io/name: form-recognizer
    app.kubernetes.io/instance: layout
    app.kubernetes.io/version: "3.1"
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  apikey: "<SET_ME>"
  billing: "<SET_ME>"

