apiVersion: v1
kind: Secret
metadata:
  name: azure-docintel-layout-secret
  labels:
    app.kubernetes.io/name: azure-docintel-layout
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "3.1"
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  apikey: "<SET_ME>"
  billing: "<SET_ME>"

