{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure-docintel-layout.secretName" . }}
  labels:
    {{- include "azure-docintel-layout.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secretEnv.apikey }}
  apikey: {{ .Values.secretEnv.apikey | b64enc }}
  {{- end }}
  {{- if .Values.secretEnv.billing }}
  billing: {{ .Values.secretEnv.billing | b64enc }}
  {{- end }}
{{- end }}

